name: Update Products Cronjob - Multi Tienda

# This schedule uses cron syntax to run every 4 hours.
on:
  schedule:
    - cron: "0 */4 * * *"  # Triggers every 4 hours at minute 0.
  workflow_dispatch:     # Enables manual run if needed.

jobs:
  update_products:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Multi-Store Sync
        env:
          # Variables para HH Global
          SHOPIFY_TOKEN_HHGLOBAL: ${{ secrets.SHOPIFY_TOKEN_HHGLOBAL }}
          GRAPHQL_URL_HHGLOBAL: ${{ secrets.GRAPHQL_URL_HHGLOBAL }}
          # Variables para GNP
          SHOPIFY_TOKEN_GNP: ${{ secrets.SHOPIFY_TOKEN_GNP }}
          GRAPHQL_URL_GNP: ${{ secrets.GRAPHQL_URL_GNP }}
        run: npm start
