name: Update Products Cronjob

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update_products:
    runs-on: ubuntu-latest

    env:
      STORES: GI,HHG,PSP
      GRAPHQL_URL_GI: ${{ secrets.GRAPHQL_URL_GI }}
      SHOPIFY_TOKEN_GI: ${{ secrets.SHOPIFY_TOKEN_GI }}
      GRAPHQL_URL_HHG: ${{ secrets.GRAPHQL_URL_HHG }}
      SHOPIFY_TOKEN_HHG: ${{ secrets.SHOPIFY_TOKEN_HHG }}
      GRAPHQL_URL_PSP: ${{ secrets.GRAPHQL_URL_PSP }}
      SHOPIFY_TOKEN_PSP: ${{ secrets.SHOPIFY_TOKEN_PSP }}
      FP_AUTH_TOKEN: ${{ secrets.FP_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "24" }
      - run: npm install
      - name: Run update
        run: node index.js
